### ISSUE TITLE
Template für Folien

### ISSUE THREAD

**Issue by UweZiegenhagen** [JoshArndt1999/FOM-LaTeX#2]
Soll ich noch ein Template für Folien beisteuern? Sehen dann so ähnlich aus wie meine Folien aus der VL.

**Comment by JoshArndt1999** [comment]
Das wäre super! Vielen Dank.

**Comment by UweZiegenhagen** [comment]
OK, füge ich hinzu.

**Comment by UweZiegenhagen** [comment]
Erste Version hinzugefügt
