### ISSUE TITLE
\befehl{} vs. \befehl| |

### ISSUE THREAD

**Issue by JoshArndt1999** [JoshArndt1999/FOM-LaTeX#3]
Ein einigen Dateien wie z. B. Installation.tex ist `\befehl{}` genutzt. An anderen Stellen (z. B. Kapitel_einfuegen.tex: "`\befehl|\chapter {Name des Kapitels}|`" wiederum werden Pipes genutzt. Was genau ist der Unterschied?

**Comment by UweZiegenhagen** [comment]
\befehl{} hat leider Probleme damit, Dinge wie \befehl{\input{abc}} zu setzen, die geschweiften Klammern verwirren da wohl. Mit den Pipes gibt es an der Stelle keine Probleme.
