### ISSUE TITLE
Skript zum Kompilieren erstellen

### ISSUE THREAD

**Issue by JoshArndt1999** [JoshArndt1999/FOM-LaTeX#5]
Einige Kommilitonen haben Probleme beim Konfigurieren des Editors zum richtigen Kompilieren. Hierzu sollte ein Skript angelegt werden, welches mit im Verzeichnis liegt und alle Befehle in der richtigen Reihenfolge ausführt. Möglicherweise so: https://gist.github.com/Sciss/9fd5ac76d9b60c7d1bd3

**Comment by UweZiegenhagen** [comment]
Für welche Betriebssysteme?

**Comment by JoshArndt1999** [comment]
Zunächst einmal Windows, aufgrund des hohen Nutzeranteils.

**Comment by UweZiegenhagen** [comment]
Ich schreibe heute Abend mal einen Entwurf auf Basis von https://www.uweziegenhagen.de/?p=399

**Comment by UweZiegenhagen** [comment]
KompiliereAlles.bat wurde hinzugefügt. Für Linux und Mac OS X werd ich das am WE machen. Der Pfad ist jetzt hart auf die main.tex gesetzt, das werde ich vermutlich noch anpassen.
